name: DeityPortal
main: com.imdeity.portals.DeityPortalMain
version: 12.07.30
language: english.yml
authors: [vanZeben, ImDeity]
website: http://www.ImDeity.com/
depend: [DeityAPI]
commands:
    DeityPortal:
        aliases: []